lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views
    path('friends/', friend_list, name=''),
]

lab_2/urls.py
from django.urls import path
from .views import index,xml,json

urlpatterns = [
    path('', index, name='index'),   
    path('xml/', xml, name='xml'), 
    path('json/', json, name='json')
]

lab_3/urls.py
from django.urls import path
from .views import index,add_friend

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name='add')
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note,note_list

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add'),
    path('note-list', note_list, name='note-list')
]

lab_5/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),   
]

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
    path('lab-5/', include('lab_5.urls')),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models


# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model
    npm = models.CharField(max_length=10)
    dob = models.DateField()

    def __str__(self):
        return self.name

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    to = models.CharField(max_length=30)
    From = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    message = models.TextField(max_length=300)

    def __str__(self):
        return self.title

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from lab_1.models import Friend
from django import forms
class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = "__all__"

lab_4/forms.py
from django.forms import ModelForm
from django import forms
from lab_2.models import Note
class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'
        widget = {
            'to' : forms.TextInput(attrs={'class': 'form-control'}), 
            'From' : forms.TextInput(attrs={'class': 'form-control'}), 
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'message' : forms.Textarea(attrs={'class': 'form-control', 'id':'message'}),
        }

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Sultan Fahrezy Syahdwinata Nugraha'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 3, 6)  # TODO Implement this, format (Year, Month, Date)
npm = 2006533811  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all() # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from .models import Note
from django.http.response import HttpResponse
from django.core import serializers

# Create your views here.
def index(request):
    notes = Note.objects.all() 
    response = {'Notes': notes}
    return render(request, 'index_lab2.html', response)

def xml(request):
    notes = Note.objects.all()
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    notes = Note.objects.all()
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.shortcuts import render
from lab_1.models import Friend
from .forms import FriendForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all() # TODO Implement this
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    context = {}
    form = FriendForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/lab-3')
    context['form'] = form
    return render(request, 'lab3_form.html', context)

lab_4/views.py
from django.shortcuts import render
from lab_2.models import Note
from .forms import NoteForm
from django.http import HttpResponseRedirect

# Create your views here.


def index(request):
    notes = Note.objects.all() 
    response = {'Notes': notes}
    return render(request, 'lab4_index.html', response)

def add_note(request):
    form  = NoteForm(request.POST or None)
    context = {'form': form}
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/lab-4')
    return render(request, 'lab4_form.html', context)

def note_list(request):
    notes = Note.objects.all() 
    response = {'Notes': notes}
    return render(request, 'lab4_note_list.html', response)

lab_5/views.py
from django.shortcuts import render
from lab_2.models import Note
from django.http.response import HttpResponse
from django.core import serializers
# Create your views here.
def index(request):
    notes = Note.objects.all() 
    response = {'Notes': notes}
    return render(request, 'lab5_index.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      <!-- EXAMPLE SECTION -->
      <tr>
        <td>Asmara Nugi</td>
        <td>1706032156</td>
        <td>May 1, 1999</td>
      </tr>
      <tr>
        <td>Fadli Rais</td>
        <td>1706032370</td>
        <td>Sept 11, 1998</td>
      </tr>
      {% if friends %}
        {% for friend in friends %}
        <tr>
            <td>{{friend.name}}</td>
            <td>{{friend.npm}}</td>
            <td>{{friend.dob}}</td>
        </tr>
        {% endfor %}
      {% endif %}
      <!-- END SECTION -->
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/index_lab2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Note List</title>
        <style>
            table, tr, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            th {
                border: 1px solid black;
                background-color: rgb(47, 155, 182);
                border-collapse: collapse;
            }
        </style>
    </head>
    <body>
        <table>
            <tr ta>
                <th>Title</th>
                <th>From</th>
                <th>To</th>
                <th>Message</th>
            </tr>
            {% if Notes %}
                {% for note in Notes %}
            <tr>
                <td>{{ note.title }}</td>
                <td>{{ note.From }}</td>
                <td>{{ note.to }}</td>
                <td>{{ note.message }}</td>
            </tr>
                {% endfor %}
            {% endif %}
        </table>
    </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Add Friend</title>
    </head>
    <body>
        <form method="POST" action="">
            {% csrf_token %}
            Name: {{form.name}}<br>
            NPM: {{form.npm}}<br>
            DOB: {{form.dob}}<br>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <style>
    table, tr, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th {
        border: 1px solid black;
        background-color: rgb(47, 155, 182);
        border-collapse: collapse;
    }
</style>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      <!-- EXAMPLE SECTION -->
      <tr>
        <td>Asmara Nugi</td>
        <td>1706032156</td>
        <td>May 1, 1999</td>
      </tr>
      <tr>
        <td>Fadli Rais</td>
        <td>1706032370</td>
        <td>Sept 11, 1998</td>
      </tr>
      {% if friends %}
        {% for friend in friends %}
        <tr>
            <td>{{friend.name}}</td>
            <td>{{friend.npm}}</td>
            <td>{{friend.dob}}</td>
        </tr>
        {% endfor %}
      {% endif %}
      <!-- END SECTION -->
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Add Note</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Gudea&display=swap');            
            *:not(label, form, input, .form-control){
                box-sizing: border-box;
                margin: 0;
                padding: 0;
                font-family: 'Gudea', sans-serif;
                background-color: #32333b;
            }
            label {
                font-weight: bolder;
            }
            li, a {
                font-weight: 500;
                font-size: 16px;
                text-decoration: none;
            }
            .this {
                background-color: #2F9BB6;
                border: none;
                border-radius: 50px;
                overflow: hidden;
            }
            .this:hover {
                background-color: #32333b;
                border: none;
                border-radius: 50px;
                overflow: hidden;
            }
            .notes {
                text-align: center;
                color: white;
                padding: 10px;
            }
            .navs {
                list-style: none;
            }
            .navs li {
                display: inline-block;
                padding: 0 10px;
            }
            .navs li a{
                color: white;
                transition: all 0.3s ease 0s;
                padding:10px 10px;
            }
            .navs li a:hover {
                color: #2F9BB6;
                border-radius: 50px;
            }
            .content {
                display: flex;
                align-items: center;
                justify-content: center;
            }
            header {
                text-align: center;
                padding: 20px
            }
            .container {
                box-shadow: 4px 4px 6px 8px rgba(0, 0, 0, 0.2);
                border-radius: 5px 5px 5px 5px;
                background-color: white;
                width: 500px;
                padding: 40px;
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                text-align: left;
            }
            input {
                background-color: white;
                border: 1px solid #2F9BB6;
                border-radius: 5px 5px 5px 5px;
                color: black;
                padding: 10px 20px;
                text-decoration: none;
                margin: 4px 2px;
            }
            textarea {
                border: 1px solid #2F9BB6;
                border-radius: 5px 5px 5px 5px;
                background-color: white;
                color: black;
                padding: 10px 20px;
                text-decoration: none;
                margin: 4px 2px;
            }
            #submit {
                border: none;
                color: white;
                background-color: #2F9BB6;
            }
            #id_message {
                border: 1px solid #2F9BB6;
                border-radius: 5px 5px 5px 5px;
                background-color: white;
                color: black;
                padding: 10px 20px;
                text-decoration: none;
                margin: 4px 2px;
            }
        </style>
    </head>
    <body>
        <header>
            <h1 class="notes">NOTES</h1>
            <nav>
                <ul class="navs">
                    <li><a href="http://127.0.0.1:8000/lab-4/" >Tables</a></li>
                    <li><a href="http://127.0.0.1:8000/lab-4/add-note" class="this">Add</a></li>
                    <li><a href="http://127.0.0.1:8000/lab-4/note-list">List</a></li>
                </ul>
            </nav>
        </header>
        <form class="container" method="post" action="">
            {% csrf_token %}
            <label for="to">To = {{form.to}}</label><br>
            <label for="from">From = {{form.From}}</label><br>
            <label for="title">Title = {{form.title}}</label><br>
            <label for="message">Message = {{form.message}}</label><br>
            <input type="submit" value="Submit" id="submit">
        </form>
    </body>
</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Note List</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Gudea&display=swap');            
            *{
                box-sizing: border-box;
                margin: 0;
                padding: 0;
                font-family: 'Gudea', sans-serif;
                background-color: #32333b;
            }
            li, a {
                font-weight: 500;
                font-size: 16px;
                text-decoration: none;
            }
            .this {
                background-color: #2F9BB6;
                border: none;
                border-radius: 50px;
                overflow: hidden;
            }
            .this:hover {
                background-color: #32333b;
                border: none;
                border-radius: 50px;
                overflow: hidden;
            }
            .notes {
                text-align: center;
                color: white;
                padding: 10px;
            }
            .navs {
                list-style: none;
            }
            .navs li {
                display: inline-block;
                padding: 0 10px;
            }
            .navs li a{
                color: white;
                transition: all 0.3s ease 0s;
                padding:10px 10px;
            }
            .navs li a:hover {
                color: #2F9BB6;
                border-radius: 50px;
            }
            .content {
                display: flex;
                align-items: center;
                justify-content: center;
            }
            header {
                text-align: center;
                padding: 20px
            }
            table {
                box-shadow: 4px 4px 6px 8px rgba(0, 0, 0, 0.2);
                border-radius: 5px 5px 5px 5px;
                table-layout: fixed;
                border-collapse: collapse;
                margin: 25px 0;
                font-size: 0.9em;
                width: 95%;
                overflow: hidden;
            }
            td {
                word-wrap: break-word;
                padding: 12px 15px;
                background-color: white;
            }
            th {
                padding: 12px 15px;
                background-color: #2F9BB6;
                color: white;
                text-align: left;
                border-collapse: collapse;
            }
            tbody tr {
                border-bottom: 1px solid #dddddd;
            }
            tbody tr:last-of-type {
                border-bottom: 5px solid #2F9BB6;
            }
        </style>
    </head>
    <body>
        <header>
            <h1 class="notes">NOTES</h1>
            <nav>
                <ul class="navs">
                    <li><a href="http://127.0.0.1:8000/lab-4/" class="this">Tables</a></li>
                    <li><a href="http://127.0.0.1:8000/lab-4/add-note">Add</a></li>
                    <li><a href="http://127.0.0.1:8000/lab-4/note-list">List</a></li>
                </ul>
            </nav>
        </header>
        <div class="content">
            <table>
                <th>Title</th>
                <th>From</th>
                <th>To</th>
                <th>Message</th>
                {% if Notes %}
                    {% for note in Notes %}
                <tr>
                    <td>{{ note.title }}</td>
                    <td>{{ note.From }}</td>
                    <td>{{ note.to }}</td>
                    <td>{{ note.message }}</td>
                </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>
    </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Note List</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Gudea&display=swap');            
            *{
                box-sizing: border-box;
                margin: 0;
                padding: 0;
                font-family: 'Gudea', sans-serif;
                background-color: #32333b;
            }
            li, a {
                font-weight: 500;
                font-size: 16px;
                text-decoration: none;
            }
            .this {
                background-color: #2F9BB6;
                border: none;
                border-radius: 50px;
                overflow: hidden;
            }
            .notes {
                text-align: center;
                color: white;
                padding: 10px;
            }
            .navs {
                list-style: none;
            }
            .navs li {
                display: inline-block;
                padding: 0 10px;
            }
            .navs li a{
                color: white;
                transition: all 0.3s ease 0s;
                padding:10px 10px;
            }
            .navs li a:hover {
                color: #2F9BB6;
                border-radius: 50px;
            }
            .this:hover {
                background-color: #32333b;
                border: none;
                border-radius: 50px;
                overflow: hidden;
            }
            header {
                text-align: center;
                padding: 20px
            }
            .card {
                background-color: white;
                box-shadow: 4px 4px 6px 8px rgba(0, 0, 0, 0.2);
                border-radius: 5px 5px 5px 5px;
                margin-top: 20px;
                margin-right: 20px;
                margin-left: 20px;
                display: block;
                width: 25%;
                word-wrap: break-word;
            }
            .card-header {
                background-color: #2F9BB6;
                border-radius: 5px 5px 0 0;
                text-align: center;
                color: white;
            }
            .content {
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                align-items: stretch;
                width: 100%;
                padding: 0 10rem;
            }
            .cardContent {
                background-color: white;
                border-radius: none;
            }

        </style>
    </head>
    <body>
        <header>
            <h1 class="notes">NOTES</h1>
            <nav>
                <ul class="navs">
                    <li><a href="http://127.0.0.1:8000/lab-4/" >Tables</a></li>
                    <li><a href="http://127.0.0.1:8000/lab-4/add-note">Add</a></li>
                    <li><a href="http://127.0.0.1:8000/lab-4/note-list" class="this">List</a></li>
                </ul>
            </nav>
        </header>
        <div class="content">
            {% if Notes %}
                    {% for note in Notes %}
            <article class="card">
                <h2 class="card-header">{{note.title}}</h2>
                <div class="content-container">
                    <p class="cardContent"><b class="cardContent">From:</b> {{note.From}}</p>
                    <p class="cardContent"><b class="cardContent">To:</b> {{note.to}}</p>
                    <p class="cardContent"><b class="cardContent">Message:</b></p>
                    <p class="cardContent" id="last">{{note.message}}</p>
                </div>
                
            </article>
                {% endfor %}
            {% endif %}
        </div>
    </body>
</html>

lab_4/templates/tutorial.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tutorial CSS Yay</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'tutorial.css' %}">
    </head>
    <body>
        <div>
            <h1>Tutorial CSS Yay</h1>
        </div>
        <div id="main">
          <div>
              <p>published: 04 Oktober 2021</p>
              <h1><a href="">Tutorial CSS ku</a></h1>
              <p>Yay ini tutorial yang gampang!</p>
          </div>
        </div>
    </body>
</html>

lab_5/templates/lab5_index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Note List</title>
        <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous">
        </script>
        <style>
            table, tr, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            th {
                border: 1px solid black;
                background-color: rgb(47, 155, 182);
                border-collapse: collapse;
            }
        </style>
    </head>
    <body>
        <table>
            <tr ta>
                <th>Title</th>
                <th>From</th>
                <th>To</th>
                <th>Message</th>
                <th>Action</th>
            </tr>
            {% if Notes %}
                {% for note in Notes %}
            <tr>
                <td>{{ note.title }}</td>
                <td>{{ note.From }}</td>
                <td>{{ note.to }}</td>
                <td>{{ note.message }}</td>
                <td>
                    <button type="button">View</button><br/>
                    <button type="button">Edit</button><br/>
                    <button type="button">Delete</button>
                </td>
            </tr>
                {% endfor %}
            {% endif %}
        </table>
    </body>
</html>